export default [
    {
        id: 1,
        title: 'Pilgrim Community Church',
        images: ['pilgrim-church-01.png', 'pilgrim-church-02-mobile.png', 'pilgrim-church-03-mobile.png',
            'pilgrim-church-04.png', 'pilgrim-church-05.png', 'pilgrim-church-06.png', 'pilgrim-church-07.png', 'pilgrim-church-09.png', 'pilgrim-church-10.png'],
        languages: ['WordPress', 'JavaScript', 'Bootstrap', 'jQuery'],
        url: 'https://github.com/ccho21/pilgrim-church',
        description : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, ipsum sapiente aspernatur libero repellat quis consequatur ducimus quam nisi',
        created_at: "2019-03-25T12:33:25-04:00",
        updated_at: "2019-04-13T13:20:03-04:00",
    },
    {
        id: 2,
        title: 'Fictional University',
        images: ['fictional-university-main-01.png', 'fictional-university-main-02.png', 'fictional-university-main-03.png', 'fictional-university-main-04.png', 'fictional-university-main-05.png'],
        languages: ['WordPress', 'JavaScript', 'Bootstrap', 'jQuery'],
        url: 'https://github.com/ccho21/fictional-univeristy',
        description : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, ipsum sapiente aspernatur libero repellat quis consequatur ducimus quam nisi',
        created_at: "2019-03-25T12:33:25-04:00",
        updated_at: "2019-04-13T13:20:03-04:00",
    },
    {
        id: 3,
        title: 'MineSweeper',
        images: ['MineSweeper-01.png', 'MineSweeper-02.png', 'MineSweeper-03.png', 'MineSweeper-04.png'],
        languages: ['JavaScript', 'Vue'],
        url: 'https://github.com/ccho21/minesweeper',
        description : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, ipsum sapiente aspernatur libero repellat quis consequatur ducimus quam nisi',
        created_at: "2019-03-25T12:33:25-04:00",
        updated_at: "2019-04-13T13:20:03-04:00",
    },
    {
        id: 4,
        title: 'Forkify',
        images: ['Forkify.png'],
        languages: ['JavaScript'],
        url: 'https://github.com/ccho21/forkify',
        description : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, ipsum sapiente aspernatur libero repellat quis consequatur ducimus quam nisi',
        created_at: "2019-03-25T12:33:25-04:00",
        updated_at: "2019-04-13T13:20:03-04:00",
    },
    {
        id: 5,
        title: 'Nators',
        images: ['Nators.png'],
        languages: ['SASS', 'JavaScript'],
        url: 'https://github.com/ccho21/Nators',
        description : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, ipsum sapiente aspernatur libero repellat quis consequatur ducimus quam nisi',
        created_at: "2019-03-25T12:33:25-04:00",
        updated_at: "2019-04-13T13:20:03-04:00",
    },
    {
        id: 6,
        title: 'Trillio',
        images: ['Trillio.png'],
        languages: ['SASS', 'JavaScript'],
        url: 'https://github.com/ccho21/Trillio',
        description : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, ipsum sapiente aspernatur libero repellat quis consequatur ducimus quam nisi',
        created_at: "2019-03-25T12:33:25-04:00",
        updated_at: "2019-04-13T13:20:03-04:00",
    }
];
